#!/bin/sh                                                                                       

PID="org.webosinternals.stella"
STELLA="/media/internal/stella"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/etc/event.d/${PID} /etc/event.d/${PID}

# create stella dirs (stella doesn't)
mkdir -p $STELLA/config $STELLA/roms $STELLA/screenshots

# install the default config
cp $IPKG_OFFLINE_ROOT/usr/palm/applications/${PID}/etc/stellarc $STELLA/config/

exit 0

